language: scala

scala:
   - 2.11.7

jdk:
  - openjdk8

env:
  - IDEA_VERSION=IC-192.5728.98

script:
  - ./gradlew --console plain check verifyPlugin

jobs:
  include:
    - stage: release
      if: tag IS present
      script:
        - ./gradlew --console plain publishPlugin
